/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "Buffer.h"

typedef struct J4AC_com_media_gankers_medianative_Buffer {
    jclass id;

    jmethodID constructor_Buffer;
} J4AC_com_media_gankers_medianative_Buffer;
static J4AC_com_media_gankers_medianative_Buffer class_J4AC_com_media_gankers_medianative_Buffer;

jobject J4AC_com_media_gankers_medianative_Buffer__Buffer(JNIEnv *env, jlong nativeObj)
{
    return (*env)->NewObject(env, class_J4AC_com_media_gankers_medianative_Buffer.id, class_J4AC_com_media_gankers_medianative_Buffer.constructor_Buffer, nativeObj);
}

jobject J4AC_com_media_gankers_medianative_Buffer__Buffer__catchAll(JNIEnv *env, jlong nativeObj)
{
    jobject ret_object = J4AC_com_media_gankers_medianative_Buffer__Buffer(env, nativeObj);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_media_gankers_medianative_Buffer__Buffer__asGlobalRef__catchAll(JNIEnv *env, jlong nativeObj)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_media_gankers_medianative_Buffer__Buffer__catchAll(env, nativeObj);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

int J4A_loadClass__J4AC_com_media_gankers_medianative_Buffer(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_media_gankers_medianative_Buffer.id != NULL)
        return 0;

    sign = "com/media/gankers/medianative/Buffer";
    class_J4AC_com_media_gankers_medianative_Buffer.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_media_gankers_medianative_Buffer.id == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_Buffer.id;
    name     = "<init>";
    sign     = "(J)V";
    class_J4AC_com_media_gankers_medianative_Buffer.constructor_Buffer = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_Buffer.constructor_Buffer == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.media.gankers.medianative.Buffer");
    ret = 0;
fail:
    return ret;
}
