/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "camera_wrapper.h"

typedef struct J4AC_com_media_gankers_medianative_CameraWrapper {
    jclass id;

    jmethodID constructor_CameraWrapper;
    jmethodID method_getExceptionMessage;
    jmethodID method_open;
    jmethodID method_getNumOfCamera;
    jmethodID method_getFrontCameraIdx;
    jmethodID method_getBackCameraIdx;
    jmethodID method_updateImage;
    jmethodID method_startPreview;
    jmethodID method_release;
} J4AC_com_media_gankers_medianative_CameraWrapper;
static J4AC_com_media_gankers_medianative_CameraWrapper class_J4AC_com_media_gankers_medianative_CameraWrapper;

jobject J4AC_com_media_gankers_medianative_CameraWrapper__CameraWrapper(JNIEnv *env, jlong nativeHandle)
{
    return (*env)->NewObject(env, class_J4AC_com_media_gankers_medianative_CameraWrapper.id, class_J4AC_com_media_gankers_medianative_CameraWrapper.constructor_CameraWrapper, nativeHandle);
}

jobject J4AC_com_media_gankers_medianative_CameraWrapper__CameraWrapper__catchAll(JNIEnv *env, jlong nativeHandle)
{
    jobject ret_object = J4AC_com_media_gankers_medianative_CameraWrapper__CameraWrapper(env, nativeHandle);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_com_media_gankers_medianative_CameraWrapper__CameraWrapper__asGlobalRef__catchAll(JNIEnv *env, jlong nativeHandle)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_com_media_gankers_medianative_CameraWrapper__CameraWrapper__catchAll(env, nativeHandle);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jstring J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getExceptionMessage);
}

jstring J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__catchAll(JNIEnv *env, jobject thiz)
{
    jstring ret_object = J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jstring J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jstring ret_object   = NULL;
    jstring local_object = J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

const char *J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage(env, thiz);
    if (J4A_ExceptionCheck__throwAny(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__throwAny(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

const char *J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_com_media_gankers_medianative_CameraWrapper__getExceptionMessage__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__catchAll(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

jboolean J4AC_com_media_gankers_medianative_CameraWrapper__open(JNIEnv *env, jobject thiz, jint idx)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_open, idx);
}

jboolean J4AC_com_media_gankers_medianative_CameraWrapper__open__catchAll(JNIEnv *env, jobject thiz, jint idx)
{
    jboolean ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__open(env, thiz, idx);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getNumOfCamera(JNIEnv *env)
{
    return (*env)->CallStaticIntMethod(env, class_J4AC_com_media_gankers_medianative_CameraWrapper.id, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getNumOfCamera);
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getNumOfCamera__catchAll(JNIEnv *env)
{
    jint ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__getNumOfCamera(env);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getFrontCameraIdx(JNIEnv *env)
{
    return (*env)->CallStaticIntMethod(env, class_J4AC_com_media_gankers_medianative_CameraWrapper.id, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getFrontCameraIdx);
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getFrontCameraIdx__catchAll(JNIEnv *env)
{
    jint ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__getFrontCameraIdx(env);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getBackCameraIdx(JNIEnv *env)
{
    return (*env)->CallStaticIntMethod(env, class_J4AC_com_media_gankers_medianative_CameraWrapper.id, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getBackCameraIdx);
}

jint J4AC_com_media_gankers_medianative_CameraWrapper__getBackCameraIdx__catchAll(JNIEnv *env)
{
    jint ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__getBackCameraIdx(env);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jlong J4AC_com_media_gankers_medianative_CameraWrapper__updateImage(JNIEnv *env, jobject thiz)
{
    return (*env)->CallLongMethod(env, thiz, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_updateImage);
}

jlong J4AC_com_media_gankers_medianative_CameraWrapper__updateImage__catchAll(JNIEnv *env, jobject thiz)
{
    jlong ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__updateImage(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jboolean J4AC_com_media_gankers_medianative_CameraWrapper__startPreview(JNIEnv *env, jobject thiz, jint tex)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_startPreview, tex);
}

jboolean J4AC_com_media_gankers_medianative_CameraWrapper__startPreview__catchAll(JNIEnv *env, jobject thiz, jint tex)
{
    jboolean ret_value = J4AC_com_media_gankers_medianative_CameraWrapper__startPreview(env, thiz, tex);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

void J4AC_com_media_gankers_medianative_CameraWrapper__release(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_media_gankers_medianative_CameraWrapper.method_release);
}

void J4AC_com_media_gankers_medianative_CameraWrapper__release__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_com_media_gankers_medianative_CameraWrapper__release(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_media_gankers_medianative_CameraWrapper(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.id != NULL)
        return 0;

    sign = "com/media/gankers/medianative/CameraWrapper";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.id == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "<init>";
    sign     = "(J)V";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.constructor_CameraWrapper = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.constructor_CameraWrapper == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "getExceptionMessage";
    sign     = "()Ljava/lang/String;";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getExceptionMessage = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getExceptionMessage == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "open";
    sign     = "(I)Z";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_open = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_open == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "getNumOfCamera";
    sign     = "()I";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getNumOfCamera = J4A_GetStaticMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getNumOfCamera == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "getFrontCameraIdx";
    sign     = "()I";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getFrontCameraIdx = J4A_GetStaticMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getFrontCameraIdx == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "getBackCameraIdx";
    sign     = "()I";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getBackCameraIdx = J4A_GetStaticMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_getBackCameraIdx == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "updateImage";
    sign     = "()J";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_updateImage = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_updateImage == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "startPreview";
    sign     = "(I)Z";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_startPreview = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_startPreview == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_CameraWrapper.id;
    name     = "release";
    sign     = "()V";
    class_J4AC_com_media_gankers_medianative_CameraWrapper.method_release = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_CameraWrapper.method_release == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.media.gankers.medianative.CameraWrapper");
    ret = 0;
fail:
    return ret;
}
