/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "i_deliver.h"

typedef struct J4AC_com_media_gankers_medianative_IDeliver {
    jclass id;

    jmethodID method_deliver;
} J4AC_com_media_gankers_medianative_IDeliver;
static J4AC_com_media_gankers_medianative_IDeliver class_J4AC_com_media_gankers_medianative_IDeliver;

void J4AC_com_media_gankers_medianative_IDeliver__deliver(JNIEnv *env, jobject thiz, jobject buffer, jint type)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_com_media_gankers_medianative_IDeliver.method_deliver, buffer, type);
}

void J4AC_com_media_gankers_medianative_IDeliver__deliver__catchAll(JNIEnv *env, jobject thiz, jobject buffer, jint type)
{
    J4AC_com_media_gankers_medianative_IDeliver__deliver(env, thiz, buffer, type);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_media_gankers_medianative_IDeliver(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_media_gankers_medianative_IDeliver.id != NULL)
        return 0;

    sign = "com/media/gankers/medianative/IDeliver";
    class_J4AC_com_media_gankers_medianative_IDeliver.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_media_gankers_medianative_IDeliver.id == NULL)
        goto fail;

    class_id = class_J4AC_com_media_gankers_medianative_IDeliver.id;
    name     = "deliver";
    sign     = "(Lcom/media/gankers/medianative/Buffer;I)V";
    class_J4AC_com_media_gankers_medianative_IDeliver.method_deliver = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_media_gankers_medianative_IDeliver.method_deliver == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.media.gankers.medianative.IDeliver");
    ret = 0;
fail:
    return ret;
}
